/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(nano_MediaCommand, nano_MediaCommand, AUTO)


PB_BIND(nano_MediaInfo, nano_MediaInfo, AUTO)


PB_BIND(nano_CommandPacket, nano_CommandPacket, AUTO)







